### ISSUE TITLE
fermodel.py

### ISSUE THREAD

**Issue by do-sa** [PradyumnaKrishna/FER#1]
i want to use emotion recognition in these emotion subset neutral,anger,fear,happiness,sadness , by fermodel how can i create this h5 and h5d5 files of this emotion subset

**Comment by PradyumnaKrishna** [comment]
You have to train the ML model in order to create h5 files. See https://github.com/PradyumnaKrishna/FER/blob/main/Model%20Training/Training.ipynb. You can also use trained models present in the directory, which is a h5 file.
